#!/usr/bin/bash

#start awwww
awww query || awww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
if [ $THEMEIS == "dark.css" ]; then
    awww img /home/yaroslav/.config/HyprV/theme.jpg
else
    awww img /home/yaroslav/.config/HyprV/wallpaper-dark.jpg
fi
